return {
    ru = {
        CHARACTER_TITLES = "Охотник ночи",
        CHARACTER_NAMES = "Owlette",
        CHARACTER_DESCRIPTIONS = "*Отличный охотник на дичь\n*Может спать только днём\n*Предпочитает мясные блюда\n*Слабая днем",
        CHARACTER_QUOTES = "\"У-ууу\"",
        CHARACTER_SURVIVABILITY = "Slim",

        NAME_OWLETTE = "Owlette",
        SKIN_OWLETTE_NONE = "Owlette",

        NAMES_OWLETTE_FEATHER = "Совиное перо",
        DESCRIBE_OWLETTE_FEATHER = "Мягкое пёрышко с Оулетты.",
        NAMES_OWLETTE_CLAWS = "Когти",
        DESCRIBE_OWLETTE_CLAWS = "Острые совиные когти.",

        SCRATCH_BURROW = "Выманить",
        EMPTY_BURROW = "Нора пуста.",

        ANNOUNCE_NONIGHTSLEEP = "Я могу спать только днём!",
        ANNOUNCE_NONIGHTSLEEP_CAVE = "Здесь не поймёшь, день или ночь!",
        ANNOUNCE_NONIGHTSIESTA = "Ночь для сна, а не для сиесты.",
        ANNOUNCE_NONIGHTSIESTA_CAVE = "Вряд ли я смогу тут расслабиться.",

        SKILLTREE = {
            HUNTING_HEADER = "Охота",
            CLAWS_HEADER = "Когти",
            NIGHT_ADVANTAGE_HEADER = "Ночное\nпреимущество",
            FLIGHT_HEADER = "Полёт",
            FEATHERS_HEADER = "Оперение",
            HUNTING_1_TITLE = "Охота",
            HUNTING_1_DESC = "занятые кроликом норы, будут подсвечены. Лучшая видимость следов коалослона",
            HUNTING_2_TITLE = "Выманивание",
            HUNTING_2_DESC = "Скребите когтями у норы, чтобы выманить кролика.",
            HUNTING_3_TITLE = "Тихий полёт",
            HUNTING_3_DESC = "Кролики и Коалослоны не слышат приближающейся опасности.",
            HUNTING_4_TITLE = "Птицелов",
            HUNTING_4_DESC = "Птицы не улетают при приближении.",
            HUNTING_5_TITLE = "Двойная добыча",
            HUNTING_5_DESC = "50% шанс получить вдвое больше лута с мелких существ.",

            NIGHTVISION_1_TITLE = "Совиное зрение",
            NIGHTVISION_1_DESC = "Глаза совы не знают тьмы — Оулетта видит каждый уголок даже в самую безлунную ночь.",
            NIGHTVISION_2_TITLE = "Ночная скорость",
            NIGHTVISION_2_DESC = "+15% к скорости бега ночью и в сумерках.",
            NIGHTVISION_3_TITLE = "Ночной хищник",
            NIGHTVISION_3_DESC = "+15% к урону ночью и в сумерках.",
            NIGHTVISION_4_TITLE = "Ночной перекус",
            NIGHTVISION_4_DESC = "Еда даёт в 1.5 раза больше здоровья, сытости и рассудка ночью и в сумерках.",

            CLAWS_1_TITLE = "Когти наточены",
            CLAWS_1_DESC = "Базовый урон когтей увеличен до 38.",
            CLAWS_2_TITLE = "Хлёсткий удар",
            CLAWS_2_DESC = "Скорость атаки когтями увеличена на 15%.",
            CLAWS_3_TITLE = "Когти отполированы",
            CLAWS_3_DESC = "Базовый урон когтей увеличен до 42.",
            CLAWS_4_TITLE = "Разрез",
            CLAWS_4_DESC = "10% шанс наложить кровотечение (10 урона/сек на 3 сек).",
            CLAWS_5_TITLE = "Улучшенный разрез",
            CLAWS_5_DESC = "15% шанс кровотечения (15 урона/сек на 3 сек).",

            FLIGHT_1_TITLE = "Взмах крыльев",
            FLIGHT_1_DESC = "Рывок на 3 тайла. Перезарядка 8 сек.",
            FLIGHT_2_TITLE = "Быстрое крыло",
            FLIGHT_2_DESC = "Перезарядка рывка снижена до 6 сек.",
            FLIGHT_3_TITLE = "Планирование",
            FLIGHT_3_DESC = "После рывка +25% к скорости на 3 сек.",
            FLIGHT_4_TITLE = "Длинное крыло",
            FLIGHT_4_DESC = "Дальность рывка увеличена до 4 тайлов.",
        FLIGHT_5_TITLE = "Стремительное крыло",
        FLIGHT_5_DESC = "Рывок намного быстрее. Дальность увеличена до 5 тайлов.",

        FEATHERS_1_TITLE = "Густое оперение",
            FEATHERS_1_DESC = "+60 к изоляции от холода.",
            FEATHERS_2_TITLE = "Водоотталкивающие перья",
            FEATHERS_2_DESC = "Скорость намокания снижена на 40%.",
            FEATHERS_3_TITLE = "Пуховой подшёрсток",
            FEATHERS_3_DESC = "Заменяет \"Густое оперение\": изоляция увеличена до +135.",
            FEATHERS_4_TITLE = "Сухое перо",
            FEATHERS_4_DESC = "Скорость высыхания увеличена вдвое.",
            FEATHERS_5_TITLE = "Линька",
            FEATHERS_5_DESC = "Каждые 2 дня Совиное перо появляется в инвентаре.",
        },
    },

    en = {
        CHARACTER_TITLES = "The night hunter",
        CHARACTER_NAMES = "Owlette",
        CHARACTER_DESCRIPTIONS = "*Excellent game hunter\n*Can only sleep during the day\n*Prefers meat dishes\n*Weak during the day",
        CHARACTER_QUOTES = "\"Hoot\"",
        CHARACTER_SURVIVABILITY = "Slim",

        NAME_OWLETTE = "Owlette",
        SKIN_OWLETTE_NONE = "Owlette",

        NAMES_OWLETTE_FEATHER = "Owl Feather",
        DESCRIBE_OWLETTE_FEATHER = "A soft feather from Owlette.",
        NAMES_OWLETTE_CLAWS = "Claws",
        DESCRIBE_OWLETTE_CLAWS = "Sharp owl Claws.",

        SCRATCH_BURROW = "Lure",
        EMPTY_BURROW = "The burrow is empty.",

        ANNOUNCE_NONIGHTSLEEP = "I can only sleep during the day!",
        ANNOUNCE_NONIGHTSLEEP_CAVE = "I can't tell time down here!",
        ANNOUNCE_NONIGHTSIESTA = "Night is for sleeping, not taking siestas.",
        ANNOUNCE_NONIGHTSIESTA_CAVE = "I don't think I could really relax down here.",

        SKILLTREE = {
            HUNTING_HEADER = "Hunting",
            CLAWS_HEADER = "Claws",
            NIGHT_ADVANTAGE_HEADER = "Night\nadvantage",
            FLIGHT_HEADER = "Flight",
            FEATHERS_HEADER = "Plumage",
            HUNTING_1_TITLE = "Hunting",
            HUNTING_1_DESC = "Rabbit burrows are highlighted. Better koalefant track visibility.",
            HUNTING_2_TITLE = "Luring",
            HUNTING_2_DESC = "Scratch at burrows to flush out rabbits.",
            HUNTING_3_TITLE = "Silent Flight",
            HUNTING_3_DESC = "Rabbits and Koalefants don't hear you coming.",
            HUNTING_4_TITLE = "Bird Catcher",
            HUNTING_4_DESC = "Birds don't flee when approached.",
            HUNTING_5_TITLE = "Double Loot",
            HUNTING_5_DESC = "50% chance to get double loot from small creatures.",

            NIGHTVISION_1_TITLE = "Owl Vision",
            NIGHTVISION_1_DESC = "Owl eyes know no darkness — Owlette sees every corner even on the darkest night.",
            NIGHTVISION_2_TITLE = "Night Speed",
            NIGHTVISION_2_DESC = "+15% movement speed at night and dusk.",
            NIGHTVISION_3_TITLE = "Night Predator",
            NIGHTVISION_3_DESC = "+15% damage at night and dusk.",
            NIGHTVISION_4_TITLE = "Night Snack",
            NIGHTVISION_4_DESC = "Food gives 1.5x more health, hunger, and sanity at night and dusk.",

            CLAWS_1_TITLE = "Sharpened Claws",
            CLAWS_1_DESC = "Claws base damage increased to 38.",
            CLAWS_2_TITLE = "Snap Strike",
            CLAWS_2_DESC = "Claws attack speed increased by 15%.",
            CLAWS_3_TITLE = "Polished Claws",
            CLAWS_3_DESC = "Claws base damage increased to 42.",
            CLAWS_4_TITLE = "Laceration",
            CLAWS_4_DESC = "10% chance to inflict bleed (10 DPS for 3 sec).",
            CLAWS_5_TITLE = "Deep Laceration",
            CLAWS_5_DESC = "15% chance to inflict bleed (15 DPS for 3 sec).",

            FLIGHT_1_TITLE = "Wing Flap",
            FLIGHT_1_DESC = "Dash 3 tiles. 8 sec cooldown.",
            FLIGHT_2_TITLE = "Swift Wing",
            FLIGHT_2_DESC = "Dash cooldown reduced to 6 sec.",
            FLIGHT_3_TITLE = "Gliding",
            FLIGHT_3_DESC = "After dashing, +25% movement speed for 3 sec.",
            FLIGHT_4_TITLE = "Long Wing",
            FLIGHT_4_DESC = "Dash distance increased to 4 tiles.",
        FLIGHT_5_TITLE = "Rapid Wing",
        FLIGHT_5_DESC = "Dash  is much faster. Distance increased to 5 tiles.",

        FEATHERS_1_TITLE = "Thick Plumage",
            FEATHERS_1_DESC = "+60 insulation from cold.",
            FEATHERS_2_TITLE = "Waterproof Feathers",
            FEATHERS_2_DESC = "Wetness rate reduced by 40%.",
            FEATHERS_3_TITLE = "Downy Undercoat",
            FEATHERS_3_DESC = "Replaces \"Thick Plumage\": insulation increased to +135.",
            FEATHERS_4_TITLE = "Dry Feather",
            FEATHERS_4_DESC = "Drying rate doubled.",
            FEATHERS_5_TITLE = "Molting",
            FEATHERS_5_DESC = "Every 2 days, an Owl Feather appears in your inventory.",
        },
    },
}