return {
    ru = {
        CHARACTER_TITLES = "Будучи ночным созданием, Оулетта обретает наибольшую силу, когда луна стоит высоко в небе.",
        CHARACTER_NAMES = "Owlette",
        CHARACTER_DESCRIPTIONS = "*Perk 1\n*Perk 2\n*Perk 3",
        CHARACTER_QUOTES = "\"У-ууу\"",
        CHARACTER_SURVIVABILITY = "Slim",

        NAME_OWLETTE = "Owlette",
        SKIN_OWLETTE_NONE = "Owlette",

        NAMES_OWLETTE_FEATHER = "Совиное перо",
        DESCRIBE_OWLETTE_FEATHER = "Мягкое пёрышко с Оулетты.",
        NAMES_OWLETTE_CLAWS = "Когти",
        DESCRIBE_OWLETTE_CLAWS = "Острые совиные когти.",

        SCRATCH_BURROW = "Выманить",
        EMPTY_BURROW = "Нора пуста.",

        SKILLTREE = {
            HUNTING_1_TITLE = "Охота",
            HUNTING_1_DESC = "занятые кроликом норы, будут подсвечены. Лучшая видимость следов коалослона",
            HUNTING_2_TITLE = "Выманивание",
            HUNTING_2_DESC = "Скребите когтями у норы, чтобы выманить кролика.",
            HUNTING_3_TITLE = "Тихий полёт",
            HUNTING_3_DESC = "Кролики и Коалослоны не слышат приближающейся опасности.",
            HUNTING_4_TITLE = "Птицелов",
            HUNTING_4_DESC = "Птицы не улетают при приближении.",
            HUNTING_5_TITLE = "Двойная добыча",
            HUNTING_5_DESC = "50% шанс получить вдвое больше лута с мелких существ.",

            NIGHTVISION_1_TITLE = "Ночное преимущество",
            NIGHTVISION_1_DESC = "Глаза совы не знают тьмы — Оулетта видит каждый уголок даже в самую безлунную ночь.",
            NIGHTVISION_2_TITLE = "Ясная ночь",
            NIGHTVISION_2_DESC = "Радиус ночного зрения увеличен до 8 тайлов.",
            NIGHTVISION_3_TITLE = "Все вижу",
            NIGHTVISION_3_DESC = "Радиус ночного зрения увеличен до 10 тайлов.",
            NIGHTVISION_4_TITLE = "Совиная зоркость",
            NIGHTVISION_4_DESC = "Радиус ночного зрения увеличен до 12 тайлов.",

            CLAWS_1_TITLE = "Когти наточены",
            CLAWS_1_DESC = "Базовый урон когтей увеличен до 38.",
            CLAWS_2_TITLE = "Хлёсткий удар",
            CLAWS_2_DESC = "Скорость атаки когтями увеличена на 15%.",
            CLAWS_3_TITLE = "Когти отполированы",
            CLAWS_3_DESC = "Базовый урон когтей увеличен до 42.",
            CLAWS_4_TITLE = "Разрез",
            CLAWS_4_DESC = "10% шанс наложить кровотечение (10 урона/сек на 3 сек).",
            CLAWS_5_TITLE = "Улучшенный разрез",
            CLAWS_5_DESC = "15% шанс кровотечения (15 урона/сек на 3 сек).",

            FLIGHT_1_TITLE = "Взмах крыльев",
            FLIGHT_1_DESC = "Рывок на 3 тайла. Перезарядка 8 сек.",
            FLIGHT_2_TITLE = "Быстрое крыло",
            FLIGHT_2_DESC = "Перезарядка рывка снижена до 6 сек.",
            FLIGHT_3_TITLE = "Планирование",
            FLIGHT_3_DESC = "После рывка +15% к скорости на 3 сек.",
            FLIGHT_4_TITLE = "Длинное крыло",
            FLIGHT_4_DESC = "Дальность рывка увеличена до 5 тайлов.",
            FLIGHT_5_TITLE = "Стремительное крыло",
            FLIGHT_5_DESC = "Рывок на 40% быстрее. Дальность увеличена до 6 тайлов.",

            FEATHERS_1_TITLE = "Густое оперение",
            FEATHERS_1_DESC = "+30 к изоляции от холода.",
            FEATHERS_2_TITLE = "Водоотталкивающие перья",
            FEATHERS_2_DESC = "Скорость намокания снижена на 20%.",
            FEATHERS_3_TITLE = "Пуховой подшёрсток",
            FEATHERS_3_DESC = "+40 к изоляции от холода (всего +70).",
            FEATHERS_4_TITLE = "Перьевой кокон",
            FEATHERS_4_DESC = "Скорость высыхания увеличена на 25%.",
            FEATHERS_5_TITLE = "Непробиваемые перья",
            FEATHERS_5_DESC = "+15% врождённого сопротивления физическому урону.",
        },
    },

    en = {
        CHARACTER_TITLES = "A creature of the night, Owlette is strongest when the moon is high.",
        CHARACTER_NAMES = "Owlette",
        CHARACTER_DESCRIPTIONS = "*Perk 1\n*Perk 2\n*Perk 3",
        CHARACTER_QUOTES = "\"Hoot\"",
        CHARACTER_SURVIVABILITY = "Slim",

        NAME_OWLETTE = "Owlette",
        SKIN_OWLETTE_NONE = "Owlette",

        NAMES_OWLETTE_FEATHER = "Owl Feather",
        DESCRIBE_OWLETTE_FEATHER = "A soft feather from Owlette.",
        NAMES_OWLETTE_CLAWS = "Talon Gauntlets",
        DESCRIBE_OWLETTE_CLAWS = "Sharp owl talons.",

        SCRATCH_BURROW = "Lure",
        EMPTY_BURROW = "The burrow is empty.",

        SKILLTREE = {
            HUNTING_1_TITLE = "Hunting",
            HUNTING_1_DESC = "Rabbit burrows are highlighted. Better koalefant track visibility.",
            HUNTING_2_TITLE = "Luring",
            HUNTING_2_DESC = "Scratch at burrows to flush out rabbits.",
            HUNTING_3_TITLE = "Silent Flight",
            HUNTING_3_DESC = "Rabbits and Koalefants don't hear you coming.",
            HUNTING_4_TITLE = "Bird Catcher",
            HUNTING_4_DESC = "Birds don't flee when approached.",
            HUNTING_5_TITLE = "Double Loot",
            HUNTING_5_DESC = "50% chance to get double loot from small creatures.",

            NIGHTVISION_1_TITLE = "Night Advantage",
            NIGHTVISION_1_DESC = "Owl eyes know no darkness — Owlette sees every corner even on the darkest night.",
            NIGHTVISION_2_TITLE = "Clear Night",
            NIGHTVISION_2_DESC = "Night vision range increased to 8 tiles.",
            NIGHTVISION_3_TITLE = "All-Seeing",
            NIGHTVISION_3_DESC = "Night vision range increased to 10 tiles.",
            NIGHTVISION_4_TITLE = "Owl's Vigilance",
            NIGHTVISION_4_DESC = "Night vision range increased to 12 tiles.",

            CLAWS_1_TITLE = "Sharpened Claws",
            CLAWS_1_DESC = "Talon Gauntlets base damage increased to 38.",
            CLAWS_2_TITLE = "Snap Strike",
            CLAWS_2_DESC = "Claw attack speed increased by 15%.",
            CLAWS_3_TITLE = "Polished Claws",
            CLAWS_3_DESC = "Talon Gauntlets base damage increased to 42.",
            CLAWS_4_TITLE = "Laceration",
            CLAWS_4_DESC = "10% chance to inflict bleed (10 DPS for 3 sec).",
            CLAWS_5_TITLE = "Deep Laceration",
            CLAWS_5_DESC = "15% chance to inflict bleed (15 DPS for 3 sec).",

            FLIGHT_1_TITLE = "Wing Flap",
            FLIGHT_1_DESC = "Dash 3 tiles. 8 sec cooldown.",
            FLIGHT_2_TITLE = "Swift Wing",
            FLIGHT_2_DESC = "Dash cooldown reduced to 6 sec.",
            FLIGHT_3_TITLE = "Gliding",
            FLIGHT_3_DESC = "After dashing, +15% movement speed for 3 sec.",
            FLIGHT_4_TITLE = "Long Wing",
            FLIGHT_4_DESC = "Dash distance increased to 5 tiles.",
            FLIGHT_5_TITLE = "Rapid Wing",
            FLIGHT_5_DESC = "Dash 40% faster. Distance increased to 6 tiles.",

            FEATHERS_1_TITLE = "Thick Plumage",
            FEATHERS_1_DESC = "+30 insulation from cold.",
            FEATHERS_2_TITLE = "Waterproof Feathers",
            FEATHERS_2_DESC = "Wetness rate reduced by 20%.",
            FEATHERS_3_TITLE = "Downy Undercoat",
            FEATHERS_3_DESC = "+40 insulation from cold (total +70).",
            FEATHERS_4_TITLE = "Feather Cocoon",
            FEATHERS_4_DESC = "Drying rate increased by 25%.",
            FEATHERS_5_TITLE = "Impenetrable Feathers",
            FEATHERS_5_DESC = "+15% innate physical damage resistance.",
        },
    },
}